### ISSUE TITLE
Port the workflow to DSL2 of Nextflow

### ISSUE THREAD

**Issue by abhi18av** [bioinformatics-lab/bactopia#1]
Lets starting working on a separate branch called `dsl2-dev`

**Comment by abhi18av** [comment]
@Mxrcon , you can start working on this branch. I've created a separate branch called `dsl2`

Please initiate the process and raise a PR against the `dsl2` branch.

**Comment by Mxrcon** [comment]
Ok! I'll rise it now.

**Comment by abhi18av** [comment]
Also, let's discuss the porting strategy here. What are the steps you're planning to do for this process?

**Comment by Mxrcon** [comment]
I'm learning exactly how bactopia uses Channels and Process, then I'm thinking in some steps: 
Update all modules inclusions, Update all process gradually, and then create a workflow scope to DSL2 and order the workflow. 
I don't know if bactopia functions need to be updated, my first analyses indicates that they're updated. 
Can we move the functions from main.nf to a module file and import then? to reduce main.nf extension and make it more readable.

**Comment by abhi18av** [comment]
Cool, this seems like a good plan.

As a reference of how to modernize a pipeline, you could also use this PR https://github.com/ctmrbio/BACTpipe/pull/124

**Comment by Mxrcon** [comment]
Hey, I'll be closing this issue as we're proceeding on the main bactopia/dsl2 branch

**Comment by abhi18av** [comment]
Yup, makes sense.
