### ISSUE TITLE
Add stubs to the processes

### ISSUE THREAD

**Issue by abhi18av** [bioinformatics-lab/bactopia#2]
@Mxrcon , adding stubs to the various processes would facilitate faster iteration for #1 

You can take references from this PR here 
https://github.com/ctmrbio/BACTpipe/pull/135

**Comment by abhi18av** [comment]
Please work on a separate branch for this feature called `stubs-dev` and when you have some commits there, raise this PR against `dsl2` branch please

**Comment by Mxrcon** [comment]
Ok! i never used stub feature, but I'm reading about bactopia pipeline, but I have doubts about how the stub works, and which outputs are generated from each process

**Comment by abhi18av** [comment]
@Mxrcon , the reference will help. Think of these two tasks as a learning opportunity - you don't need to run to complete them but you can start coming up with your own ideas and doubts when you read/write NF code :)

**Comment by abhi18av** [comment]
Hi @Mxrcon, 

Let me know whenever you've added the stubs and I'd be happy to review them.

**Comment by Mxrcon** [comment]
Ok! I still working on stubs, because I'm not sure of the outputs from each process, some of them just outputs something on channels and i don't know that that variable means. I need more testing.

**Comment by abhi18av** [comment]
I've created a PR here, I'll be notified now every time you push to that branch (hence the PR).

https://github.com/bioinformatics-lab/bactopia/pull/4
